language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
before_install:
  - pip install --user codecov
install: composer install
before_script:
  - php -S localhost:8080 -t test/server/
script: phpunit --bootstrap test/bootstrap.php --configuration test/configuration.xml --coverage-clover=coverage.xml test
after_success:
  - codecov
notifications:
  email: false