language: php
php:
  - '8.0'
install: composer install
before_script:
  - export FOO=BAR
  - php -S localhost:8080 -t test/server/ > phpd.log 2>&1 &
script: phpunit --bootstrap test/bootstrap.php --configuration test/configuration.xml --coverage-clover=coverage.xml test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false