language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
install: composer install
script: phpunit --bootstrap test/bootstrap.php --configuration test/configuration.xml test
before_install:
  - pip install --user codecov
after_success:
  - codecov